#!/bin/sh
set -eu

# root path of the repositories holding configuration
# if there is no parent config,
# both variables have the same value
PARENT_REPOSITORY_ROOT="$(dirname $(githook-companion config directory))"
CHILD_REPOSITORY_ROOT="$(pwd)"
# binary dependecy directories.
# if there is no parent config,
# both variables have the same value
PARENT_BIN_DIRECTORY="$(githook-companion config dependency path)"
CHILD_BIN_DIRECTORY="$(githook-companion config dependency path --child)"
# project custom githook directory
CHILD_GITHOOKS_DIRECTORY="$(githook-companion config hook path --child)"


if [ "$(githook-companion git hook locked post-commit)" != "true" ]
then

  echo "apply parent post-commit"
  githook-companion git hook lock post-commit --duration 5m

  if [ -d "$CHILD_GITHOOKS_DIRECTORY" ] && [ -f "$CHILD_GITHOOKS_DIRECTORY/post-commit" ] && [ "$PARENT_REPOSITORY_ROOT" != "$CHILD_REPOSITORY_ROOT" ]
  then
    echo "apply child post-commit"
    "$CHILD_GITHOOKS_DIRECTORY"/post-commit
  fi

  # remove lock
  githook-companion git hook unlock post-commit
else
  echo "parent post-commit is locked"
fi
