#!/bin/sh
set -eu

# root path of the repositories holding configuration
# if there is no parent config,
# both variables have the same value
PARENT_REPOSITORY_ROOT="$(dirname $(githook-companion config directory))"
CHILD_REPOSITORY_ROOT="$(pwd)"
# binary dependecy directories.
# if there is no parent config,
# both variables have the same value
PARENT_BIN_DIRECTORY="$(githook-companion config dependency path)"
CHILD_BIN_DIRECTORY="$(githook-companion config dependency path --child)"
# project custom githook directory
CHILD_GITHOOKS_DIRECTORY="$(githook-companion config hook path --child)"


if [ "$(githook-companion git hook active post-commit)" == "true" ]
then
  # the post-commit hook can't be avoided by Git means
  # that is why we use a lock to ensure it will be run only once
  githook-companion git hook lock post-commit --duration 5m

  if [ -d "$CHILD_GITHOOKS_DIRECTORY" ] && [ -f "$CHILD_GITHOOKS_DIRECTORY/post-commit" ] && [ "$PARENT_REPOSITORY_ROOT" != "$CHILD_REPOSITORY_ROOT" ]
  then
    echo "apply child post-commit"
    "$CHILD_GITHOOKS_DIRECTORY"/post-commit
  fi

  echo "apply parent post-commit"

  # generating changelog
  TEMPLATE_NAME=$(githook-companion git server name --default default)
  REPOSITORY_URL=$(githook-companion git server repository)

  echo "generating CHANGELOG.md for $REPOSITORY_URL with template $PARENT_REPOSITORY_ROOT/.chglog/templates/$TEMPLATE_NAME.tpl.md"
  git fetch --prune --prune-tags --tags -f origin
  "$PARENT_BIN_DIRECTORY"/git-chglog \
      --next-tag 'Unreleased' \
      --repository-url "$REPOSITORY_URL" \
      -o "$CHILD_REPOSITORY_ROOT/CHANGELOG.md" \
      -c "$PARENT_REPOSITORY_ROOT/.chglog/config.yml" \
      -t "$PARENT_REPOSITORY_ROOT/.chglog/templates/$TEMPLATE_NAME.tpl.md" 


  if [ -n "$(git diff CHANGELOG.md)" ] || [ -z "$(git ls-files CHANGELOG.md)" ]; then
    echo "commit changes to the changelog file"

    git add "CHANGELOG.md"
    git commit -m "IGNORE: CHANGELOG update at $(date +"%Y-%m-%dT%H:%M")" --no-verify --quiet --no-post-rewrite
  fi


  # remove lock
  githook-companion git hook unlock post-commit
else
  echo "parent post-commit is inactive"
fi
