#!/bin/sh
#; C:/Program\ Files/Git/usr/bin/sh.exe
set -eu

# root path of the repositories holding configuration
# if there is no parent config,
# both variables have the same value
PARENT_REPOSITORY_ROOT="$(dirname $(githook-companion config directory))"
CHILD_REPOSITORY_ROOT="$(pwd)"
# binary dependecy directories.
# if there is no parent config,
# both variables have the same value
PARENT_BIN_DIRECTORY="$(githook-companion config dependency path)"
CHILD_BIN_DIRECTORY="$(githook-companion config dependency path --child)"
# project custom githook directory
CHILD_GITHOOKS_DIRECTORY="$(githook-companion config hook path --child)"


# apply custom git-hooks
if [ -d "$CHILD_GITHOOKS_DIRECTORY" ] && [ -f "$CHILD_GITHOOKS_DIRECTORY/pre-push" ] && [ "$PARENT_REPOSITORY_ROOT" != "$CHILD_REPOSITORY_ROOT" ]
then
  echo "apply child pre-push"
  "$CHILD_GITHOOKS_DIRECTORY"/pre-push
fi

echo "apply generic pre-push"

# make sure a clean state is being pushed
if [ -z "$(git status --porcelain)" ]; then
  # Working directory clean
  echo "clean state: proceed with push"
else
  # Uncommitted changes
  echo "you have uncommited changes: stopping the push"
  git diff
  exit 1
fi
