#!/bin/sh
set -eu

# root path of the repositories holding configuration
# if there is no parent config,
# both variables have the same value
PARENT_CONFIG_REPOSITORY="$(dirname $(githook-companion config directory))"
CHILD_CONFIG_REPOSITORY="$(pwd)"
# binary dependecy directories
BIN_DIRECTORY="$(githook-companion config dependency path)"
CHILD_BIN_DIRECTORY="$(githook-companion config dependency path --child)"
# githooks directory
CHILD_GITHOOKS_DIRECTORY="$(githook-companion config hook path --child)"
CHILD_CONFIG_DIRECTORY="$(githook-companion config directory --child)"

echo "apply generic pre-commit"

# unlock all githooks from last cycle
githook-companion git hook unlock --all

# Make sure my email is set properly
if [ -z "$(git config user.email)" ]
then
	cat "\nError: user.email not set\n\n"
	exit 1
fi

# Make sure my name is set properly
if [ -z "$(git config user.name)" ]
then
	cat "\nError: user.name not set\n\n"
	exit 1
fi

if [ -d "$CHILD_GITHOOKS_DIRECTORY" ] && [ -f "$CHILD_GITHOOKS_DIRECTORY/pre-commit" ] && [ "$PARENT_CONFIG_REPOSITORY" != "$CHILD_CONFIG_REPOSITORY" ]
then
  echo "apply child pre-commit"
  "$CHILD_GITHOOKS_DIRECTORY"/pre-commit
fi
