#!/bin/sh
set -eu

# directory where the hook was triggered (your project)
PROJECT_DIRECTORY="$(pwd)"
# directory where the hook is stored (child or parent)
CONFIGURATION_DIRECTORY="$(dirname $(dirname $(dirname $0)))"
# binary dependecy directory
BIN_DIRECTORY="$(githook-companion config dependency path)"
# githooks directory
CUSTOM_GITHOOKS_DIRECTORY="$(githook-companion config hook path)"


echo "apply parent prepare-commit-msg"

COMMIT_MESSAGE_FILE=$1
COMMIT_SOURCE=$2

# log some information for debugging
echo "$(date)" > ~/githook-companion.log
echo "-------------------------" >> ~/githook-companion.log
echo "COMMIT_MESSAGE_FILE: $COMMIT_MESSAGE_FILE" >> ~/githook-companion.log
echo "COMMIT_SOURCE:       $COMMIT_SOURCE" >> ~/githook-companion.log
echo "-------------------------" >> ~/githook-companion.log
githook-companion debug >> ~/githook-companion.log
echo "-------------------------" >> ~/githook-companion.log
env >> ~/githook-companion.log

githook-companion commit validate -m "$(cat $COMMIT_MESSAGE_FILE)" -o "$COMMIT_MESSAGE_FILE" < /dev/tty
