kind: GithookCompanionConfiguration
version: 0.8.16

dependencies:
  - name: git-chglog
    version: 0.15.4
    force-replace: true
    archive_url_template: https://github.com/git-chglog/git-chglog/releases/download/v{{.Version}}/git-chglog_{{.Version}}_{{.Os}}_{{.Arch}}.{{.Ext}}

sync:
    parent: true
    binary: true
    timeout: 5s
    checkperiod: 3m0s
    offlinelockduration: 20m0s

commit:
    types:
        - type: feat
          description: a new feature is introduced with the changes
        - type: refactor
          description: refactored code that neither fixes a bug nor adds a feature
        - type: ignore
          description: commit can be ignored by other tools
        - type: fix
          description: a bug fix has been implemented
        - type: docs
          description: documentation only changes
        - type: test
          description: including new or correcting previous tests
        - type: perf
          description: a code change that improves performance
        - type: style
          description: changes that do not affect the meaning of the code (white-space, formatting, ...)
        - type: chore
          description: other changes that don't modify src or test files
        - type: build
          description: changes that affect the build system or external dependencies
        - type: ci
          description: changes to CI configuration files and scripts
    no_formatting:
        - ignore
    default_type: feat
    message_template: '{{ .CommitType | upper }}{{ if .CommitScope }}({{ .CommitScope | lower }}){{ end }}{{ if .CommitBreakingFlag }}{{ .CommitBreakingFlag }}{{ end }}: {{ if .IssueTrackerReference }}[{{ .IssueTrackerReference }}]{{ end }} {{ .Message | lower }}'
    tokenizer_options:
        language_detection_options:
            default_language_code: en
            default_language_Name: english
            confidence_thresthold: 0.2
            minimum_word_count: 5
        language_codes:
            - en
        dictionaries:
            - name: weak-feature-signals
              description: a collection of words that can imply a new feature
              language_code: en
              token_name: commit_type
              token_value: feat
              token_value_is_match: false
              synonyms:
                - add
                - implement
                - use
                - new
              weight: 1
              confidence_thresthold: 0
            - name: ignore-signals
              description: ""
              language_code: en
              token_name: commit_type
              token_value: ignore
              token_value_is_match: false
              synonyms:
                - typo
                - wip
              weight: 2
              confidence_thresthold: 0
            - name: refactor-signals
              description: ""
              language_code: en
              token_name: commit_type
              token_value: refactor
              token_value_is_match: false
              synonyms:
                - remove
                - change
                - update
                - upgrate
                - restructure
              weight: 2
              confidence_thresthold: 0
            - name: fix-signals
              description: ""
              language_code: en
              token_name: commit_type
              token_value: fix
              token_value_is_match: false
              synonyms:
                - fix
                - bugfix
                - bug
              weight: 2
              confidence_thresthold: 0
            - name: docs-signals
              description: ""
              language_code: en
              token_name: commit_type
              token_value: docs
              token_value_is_match: false
              synonyms:
                - document
                - doc
              weight: 2
              confidence_thresthold: 0
            - name: test-signals
              description: ""
              language_code: en
              token_name: commit_type
              token_value: test
              token_value_is_match: false
              synonyms:
                - test
              weight: 2
              confidence_thresthold: 0
        lexemes:
            - name: commit_type
              description: auto-generated commit type lexeme to be retrieved from well formatted messages
              language_code: '*'
              token: commit_type
              variants:
                - name: ""
                  description: ""
                  matcher: ^(?i)(feat|refactor|ignore|fix|docs|test|perf|style|chore|build|ci)\b(\s*\(\w+\)){0,1}\s*!{0,1}\s*:{0,1}
                  normalisers: []
              splitters:
                - name: commit_type
                  description: commit type lexeme
                  token: commit_type
                  variants:
                    - name: ""
                      description: ""
                      matcher: ^(?i)(feat|refactor|ignore|fix|docs|test|perf|style|chore|build|ci)
                      normalisers: []
                  normalisers:
                    - name: ""
                      description: ""
                      matcher: ^(?i)(feat|refactor|ignore|fix|docs|test|perf|style|chore|build|ci)
                      replace_all: true
                      replacement: ""
                      formatter:
                        template: '{{ upper . }}'
                - name: commit_scope
                  description: commit scope lexeme
                  token: commit_scope
                  variants:
                    - name: ""
                      description: ""
                      matcher: \((\w+)\)
                      normalisers: []
                  normalisers:
                    - name: ""
                      description: ""
                      matcher: (\w+)
                      replace_all: true
                      replacement: ""
                      formatter:
                        template: '{{ lower . }}'
                - name: commit_breaking_flag
                  description: commit scope lexeme
                  token: commit_breaking_flag
                  variants:
                    - name: ""
                      description: ""
                      matcher: (!{0,1})
                      normalisers: []
                  normalisers:
                    - name: ""
                      description: ""
                      matcher: (!)
                      replace_all: true
                      replacement: ""
              normalisers: []
            - name: iso8601-date
              description: lexeme to identify a date formatted after ISO-8601
              language_code: '*'
              token: iso8601_date
              variants:
                - name: iso8601-date
                  description: ""
                  matcher: \d{4}(-\d\d(-\d\d(T\d\d:\d\d(:\d\d)?(\.\d+)?(([+-]\d\d:\d\d)|Z)?)?)?)?
                  normalisers:
                    - name: ISO-8601 date
                      description: ""
                      matcher: (.+)
                      replace_all: true
                      replacement: ""
                      formatter:
                        template: '{{ upper . }}'
              splitters: []
              normalisers: []
            - name: issue_tracker_reference
              description: lexeme to identify issue tracker references from different providers
              language_code: '*'
              token: issue_tracker_reference
              variants:
                - name: JIRA like issue reference
                  description: ""
                  matcher: '[\(\[]([a-zA-Z][\w]{1,6})[-_]([\d]+)[\)\]]{0,1}'
                  normalisers:
                    - name: ""
                      description: ""
                      matcher: ([a-zA-Z][\w]{1,6})[-_]([\d]+)
                      replace_all: true
                      replacement: ""
                      formatter:
                        template: '{{ upper . }}'
                    - name: ""
                      description: ""
                      matcher: '[-_]'
                      replace_all: false
                      replacement: '-'
                - name: GitHub issue reference
                  description: ""
                  matcher: '[\(\[]{0,1}(#|gh-|GH-)([\d]+)[\)\]]{0,1}'
                  normalisers:
                    - name: github issue reference
                      description: ""
                      matcher: (#)
                      replace_all: false
                      replacement: gh-
              splitters: []
              normalisers: []
        normalisers: []
        confidence_thresthold: 0
dependency_directory: ""
githook_directory: ""
